#!/usr/bin/env pwsh
# ============================================================================
# Tube Scan Plan Guide — v5 Narration Post-Processing Pipeline
# ============================================================================
# Generated by Claude on 2026-05-13.
#
# This script:
#   1. Concatenates the two ElevenLabs v5 TTS parts into one master VO file
#      with a 0.6 s silence between them (so the pause feels natural).
#   2. Reports the total duration of the new voiceover.
#   3. Optionally re-encodes the master video with the new audio track.
#
# Requires: ffmpeg in PATH (https://ffmpeg.org/download.html)
# ============================================================================

$ErrorActionPreference = "Stop"
$ProjectRoot = "C:\Users\Amita\Downloads\Scan-Master-16-12-25-main\Scan-Master-16-12-25-main"
$AudioDir   = "$ProjectRoot\training-videos\assets\tube-scan-plan\audio"
$ClaudeDir  = "$AudioDir\Claude MCP"

# ---- 1. Locate the two v5 parts (most recent two TTS files in Claude MCP/) ----
$parts = Get-ChildItem "$ClaudeDir\tts_*.mp3" | Sort-Object LastWriteTime
if ($parts.Count -lt 2) {
    Write-Error "Expected at least 2 TTS parts in $ClaudeDir, found $($parts.Count)"
    exit 1
}
$part1 = $parts[-2].FullName
$part2 = $parts[-1].FullName
Write-Host "Part 1: $part1"
Write-Host "Part 2: $part2"

# ---- 2. Create a 0.6 s silence file ----
$silence = "$env:TEMP\silence_600ms.mp3"
ffmpeg -y -f lavfi -i "anullsrc=channel_layout=mono:sample_rate=44100" -t 0.6 -c:a libmp3lame -q:a 4 $silence 2>$null
if (-not (Test-Path $silence)) {
    Write-Error "Failed to create silence file"
    exit 1
}

# ---- 3. Build concat list ----
$concatList = "$env:TEMP\v5_concat_list.txt"
@"
file '$part1'
file '$silence'
file '$part2'
"@ | Out-File -FilePath $concatList -Encoding ascii

# ---- 4. Concatenate to master VO ----
$masterVO = "$AudioDir\voiceover-tube-scan-plan-v5-master.mp3"
ffmpeg -y -f concat -safe 0 -i $concatList -c:a libmp3lame -b:a 128k -ar 48000 -ac 1 $masterVO 2>&1 | Out-Null
if (-not (Test-Path $masterVO)) {
    Write-Error "Concatenation failed"
    exit 1
}

# ---- 5. Report duration ----
$duration = (ffprobe -v error -show_entries format=duration -of csv=p=0 $masterVO).Trim()
$durationSeconds = [math]::Round([double]$duration, 2)
Write-Host ""
Write-Host "✅ Master voiceover created:"
Write-Host "   $masterVO"
Write-Host "   Duration: $durationSeconds seconds ($([math]::Floor($durationSeconds/60)):$([math]::Round($durationSeconds%60)) min)"
Write-Host ""

# ---- 6. Cleanup temp files ----
Remove-Item $silence -ErrorAction SilentlyContinue
Remove-Item $concatList -ErrorAction SilentlyContinue

Write-Host "Next steps:"
Write-Host "  1. Listen to the master VO and verify quality"
Write-Host "  2. If happy, run rebuild-video-with-v5-audio.ps1 to swap the audio"
Write-Host "     in the published video at public/videos/tube-scan-plan-tcg-calibration.mp4"
