import { emptyPtSheet, type PenetrantMethod, type PenetrantType } from '@/types/penetrant';
import {
  emptyRtDigitalSheet,
  type RtDigitalAcquisitionPlan,
  type RtDigitalPlanning,
} from '@/types/rtDigital';
import { emptyRtFilmSheet } from '@/types/rtFilm';
import {
  calculateRtDigitalPlanning,
  type RtDigitalExposureGridDescriptor,
} from '@/lib/rtDigitalPlanning';
import {
  createRtDigitalAcquisition,
  createRtFilmExposureView,
  createRtPtDocument,
} from '@/lib/rtPtDocumentCodec';
import { bindRtPtApprovedContent } from '@/lib/rtPtApprovalLifecycle';
import type { RtPtDocumentStatus, RtPtDocumentV3 } from '@/types/rtPtDocument';

const bindFixtureApproval = <T extends RtPtDocumentV3>(
  document: T,
  status: RtPtDocumentStatus,
): T => (
  status === 'approved' ? bindRtPtApprovedContent(document) as T : document
);

export const completeGeneral = {
  partName: 'Test casting',
  partNumber: 'PART-100',
  vendorCode: 'VENDOR-7',
  partRevisionOrConfiguration: 'REV-B',
  material: 'Aluminum alloy',
  surfaceFinish: 'As cast',
  inspectionArea: 'Entire part',
  thickness: 10,
  thicknessUnit: 'mm' as const,
  drawingReference: 'DWG-100 REV B',
  procedureNumber: 'PROC-NDT-1',
  inspectionStage: 'Final' as const,
  inspectorLevel: 'II' as const,
  date: '2026-07-20',
};

export const completeAcceptance = {
  acceptanceStandard: 'PRODUCT-SPEC-1',
  acceptanceClause: '7.4',
  acceptanceText: 'Apply the controlled product-specification acceptance text.',
  acceptanceClass: 'Class 2',
  acceptanceGrade: 'Grade C',
  specialRequirements: 'None',
};

const controlledBase = {
  documentId: '00000000-0000-4000-8000-000000000099',
  documentControl: {
    number: 'RTPT-100',
    title: 'Controlled NDT Technique',
    revision: 'B',
    revisionDate: '2026-07-20',
    effectiveDate: '2026-07-21',
    changeSummary: 'V3 planned technique',
  },
  revisionHistory: [{
    id: 'revision-b',
    revision: 'B',
    date: '2026-07-20',
    description: 'V3 planned technique',
    author: 'Planner',
  }],
  organization: { name: 'NDT Laboratory', site: 'Site A' },
  job: { customer: 'Customer', contract: 'C-1', purchaseOrder: 'PO-1', workOrder: 'WO-1' },
  unitSystem: 'SI' as const,
  controlledReferences: [{
    type: 'Product specification',
    title: 'Product acceptance specification',
    number: 'PRODUCT-SPEC-1',
    revision: 'B',
    clauseOrNote: 'Clause 7.4',
  }],
  approvals: [{
    role: 'ndt-level-3' as const,
    name: 'Level Three',
    personnelId: 'L3-001',
    certificationBasis: 'Written practice',
    certificationRevision: 'C',
    date: '2026-07-20',
  }],
};

const filmView = (index: number) => createRtFilmExposureView({
  id: `film-view-${index}`,
  viewId: `V${index}`,
  description: `Planned view ${index}`,
  orientation: `${(index - 1) * 90} deg`,
  inspectionZone: `Zone ${index}`,
  referenceAttachmentId: `ATT-${index}`,
  wallTechnique: 'SWSI',
  sfd: 110,
  sfdUnit: 'mm',
  sod: 100,
  sodUnit: 'mm',
  ofd: 10,
  ofdUnit: 'mm',
  thicknessDescription: 'Controlled range',
  thicknessMin: 8,
  thicknessMax: 12,
  thicknessUnit: 'mm',
  requiredUg: 0.1,
  requiredUgUnit: 'mm',
  iqiOverride: 'Use global IQI plan',
  tubeVoltage: 120,
  tubeCurrent: 5,
  exposureTime: 2,
  exposureTimeUnit: 'min',
  filter: 'None',
  collimation: 'To inspection zone',
  filmDesignation: 'FILM-A',
  filmSize: '35 x 43 cm',
  maxParts: 1,
  maxCassettes: 1,
  beamAngle: 90,
  screenOverride: 'None',
  overlap: 'Witnessed overlap required',
  identification: `Lead marker V${index}`,
  notes: 'Planned only',
});

export function createCompleteFilmDocument(status: RtPtDocumentStatus = 'draft'): Extract<RtPtDocumentV3, { method: 'RT-Film' }> {
  const document = createRtPtDocument({
    ...controlledBase,
    status,
    method: 'RT-Film',
    technique: {
      ...emptyRtFilmSheet,
      general: completeGeneral,
      exposureDefaults: {
        ...emptyRtFilmSheet.exposureDefaults,
        wallTechnique: 'SWSI',
        sfd: 110,
        sod: 100,
        ofd: 10,
        requiredUg: 0.1,
      },
      source: {
        ...emptyRtFilmSheet.source,
        sourceType: 'X-ray',
        manufacturer: 'Source Maker',
        model: 'XR-200',
        serialNumber: 'XR-SN-1',
        calibrationRequirement: 'Calibration within the controlled procedure interval',
        xRay: { focalSpotSize: 1, focalSpotSizeUnit: 'mm' },
      },
      filmSystem: {
        ...emptyRtFilmSheet.filmSystem,
        manufacturer: 'Film Maker',
        filmDesignation: 'FILM-A',
        filmClass: 'Class I',
        requiredDensityMin: 1.5,
        requiredDensityMax: 4,
        processingSystem: 'Automatic processor P-1',
        processingMethod: 'Automatic',
        processingTime: 7,
        processingTimeUnit: 'min',
        processingTemperature: 28,
        processingTemperatureTolerance: 1,
        processingTemperatureUnit: 'degC',
        frontScreen: { material: 'Lead', thickness: 0.1, thicknessUnit: 'mm' },
        backScreen: { material: 'Lead', thickness: 0.1, thicknessUnit: 'mm' },
        cassetteType: 'Rigid',
        viewingEquipment: 'Viewer V-1',
      },
      iqi: {
        ...emptyRtFilmSheet.iqi,
        type: 'Hole',
        standard: 'Controlled IQI standard',
        designation: 'IQI-10',
        shim: 'Shim S-1',
        block: 'Block B-1',
        material: 'Same alloy group',
        thickness: 10,
        placement: 'Source side',
        requiredSensitivity: 'Per controlled reference',
        imageQualityLevel: 'Per controlled reference',
        requiredUg: 0.1,
      },
      acceptance: completeAcceptance,
      exposureViews: [1, 2, 3, 4].map(filmView),
      techniqueNotes: 'All entries are planned or required values.',
    },
  }) as Extract<RtPtDocumentV3, { method: 'RT-Film' }>;
  return bindFixtureApproval(document, status);
}

export function createCompletePs811000FilmDocument(
  status: RtPtDocumentStatus = 'draft',
): Extract<RtPtDocumentV3, { method: 'RT-Film' }> {
  const document = createCompleteFilmDocument(status === 'approved' ? 'draft' : status);
  document.technique.ps811000Applicable = true;
  document.controlledReferences.push({
    type: 'Process specification',
    title: 'Controlled radiographic process specification',
    number: 'PS811000E',
    revision: 'C1',
    clauseOrNote: 'Verified calculation and lookup basis',
  });
  document.technique.filmSystem.viewingMode = 'single';
  document.technique.filmSystem.viewerOutputCandelaPerSquareMeter = 100000;
  document.technique.filmSystem.individualFilmDensityMinimum = '';
  document.technique.iqi.requiredUg = '';
  document.technique.exposureDefaults = {
    ...document.technique.exposureDefaults,
    ps811000EnergyCurve: 'aluminum-magnesium',
    ps811000EquivalenceMaterial: 'Aluminum 1100 / 6061',
    ps811000ThicknessBasis: 'entered-thickness',
    machineTechniqueReference: 'MACHINE-TABLE-1 REV A',
    coverageDiameter: 10,
    coverageDiameterUnit: 'mm',
    thicknessMin: 8,
    thicknessMax: 12,
    tubeVoltage: 70,
    tubeCurrent: 5,
    exposureTime: 2,
    exposureTimeUnit: 'min',
    requiredUg: '',
  };
  document.technique.exposureViews = document.technique.exposureViews.map((view) => ({
    ...view,
    ps811000EnergyCurve: 'aluminum-magnesium',
    ps811000EquivalenceMaterial: 'Aluminum 1100 / 6061',
    ps811000ThicknessBasis: 'entered-thickness',
    machineTechniqueReference: 'MACHINE-TABLE-1 REV A',
    coverageDiameter: 10,
    coverageDiameterUnit: 'mm',
    tubeVoltage: 70,
    requiredUg: '',
  }));
  return bindFixtureApproval(document, status);
}

const currentDigitalStatus = (reference: string) => ({
  reference,
  date: '2026-07-01',
  dueDate: '2027-07-01',
  status: 'Current',
});

const createCompleteDigitalPlanning = (): RtDigitalPlanning => ({
  id: 'digital-planning-1',
  part: {
    id: 'digital-part-1',
    partName: completeGeneral.partName,
    partNumber: completeGeneral.partNumber,
    vendorCode: completeGeneral.vendorCode,
    revisionOrConfiguration: completeGeneral.partRevisionOrConfiguration,
    drawingOrSpecificationReference: completeGeneral.drawingReference,
    procedureNumber: completeGeneral.procedureNumber,
    material: completeGeneral.material,
    materialSpecification: 'AMS 4218 REV N',
    materialGroup: 'Aluminum alloys',
    surfaceFinish: completeGeneral.surfaceFinish,
    manufacturingProcess: 'Casting',
    otherManufacturingProcess: '',
    geometry: {
      id: 'part-geometry-1',
      geometryType: 'Rectangular',
      unit: 'mm',
      length: 600,
      width: 300,
      height: 20,
    },
    thickness: {
      id: 'thickness-definition-1',
      mode: 'Multiple Thickness Zones',
      unit: 'mm',
      zones: [
        {
          id: 'thickness-zone-1',
          zoneId: 'TZ-01',
          description: 'Nominal wall zone',
          minimum: 8,
          maximum: 10,
          governing: 10,
          position: { x: 0, y: 0, width: 0.5, height: 1, rotationDegrees: 0 },
        },
        {
          id: 'thickness-zone-2',
          zoneId: 'TZ-02',
          description: 'Reinforced wall zone',
          minimum: 10,
          maximum: 12,
          governing: 12,
          position: { x: 0.5, y: 0, width: 0.5, height: 1, rotationDegrees: 0 },
        },
      ],
    },
    inspectionAreas: {
      id: 'inspection-areas-1',
      mode: 'Defined Area',
      areas: [{
        id: 'inspection-area-1',
        areaId: 'AREA-01',
        description: 'Controlled rectangular inspection footprint',
        width: 500,
        height: 250,
        unit: 'mm',
        position: { x: 0.05, y: 0.1, width: 0.9, height: 0.8, rotationDegrees: 0 },
      }],
    },
    technique: {
      wallTechnique: 'Single Wall',
      imageTechnique: 'SWSI',
      otherImageTechnique: '',
    },
    inspectionStandard: 'ASTM E2698/E2698M',
    inspectionStandardRevision: '2024',
    attachments: [{
      id: 'part-reference-1',
      name: 'PART-100-layout.pdf',
      mimeType: 'application/pdf',
      size: 4096,
      sha256: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    }],
    referenceAttachmentId: 'part-reference-1',
    partOrientation: 'Datum A down; long axis horizontal',
    datumReference: 'Drawing datum A/B/C',
  },
  sourceSelection: {
    id: 'source-selection-1',
    catalogRecordId: 'source-record-1',
    catalogRevisionId: 'source-revision-1',
    catalogRevision: 1,
    snapshot: {
      manufacturer: 'Source Maker',
      model: 'XR-200',
      serialNumber: 'XR-SN-1',
      kvMinimum: 20,
      kvMaximum: 200,
      currentMinimum: 0.1,
      currentMaximum: 10,
      maximumPowerKw: 2,
      focalSpots: [{ id: 'focal-spot-1', label: 'Standard 1 mm', size: 1, unit: 'mm' }],
      filters: [{ id: 'filter-cu-1', label: '1 mm Cu', description: 'Qualified copper beam filter' }],
      calibration: currentDigitalStatus('SOURCE-CAL-1 REV A'),
      qualification: currentDigitalStatus('SOURCE-QUAL-1 REV A'),
    },
    focalSpotOptionId: 'focal-spot-1',
    filterOptionIds: ['filter-cu-1'],
    extraFilter: '',
    notes: 'Use only the controlled catalog configuration.',
  },
  detectorSelection: {
    id: 'detector-selection-1',
    catalogRecordId: 'detector-record-1',
    catalogRevisionId: 'detector-revision-1',
    catalogRevision: 1,
    snapshot: {
      manufacturer: 'Detector Maker',
      model: 'DDA-1',
      serialNumber: 'DDA-SN-1',
      activeWidth: 400,
      activeHeight: 300,
      activeAreaUnit: 'mm',
      matrixColumns: 2000,
      matrixRows: 1500,
      pixelSize: 200,
      pixelSizeUnit: 'um',
      bitDepth: 16,
      detectorSrb: 200,
      detectorSrbUnit: 'um',
      modes: ['Full'],
      calibration: currentDigitalStatus('CAL-1'),
      badPixelMap: currentDigitalStatus('BPM-1'),
      qualification: currentDigitalStatus('DETECTOR-QUAL-1 REV A'),
    },
    detectorMode: 'Full',
    orientation: 'Landscape',
    extraMode: '',
    notes: 'Landscape orientation is the calculated minimum-exposure layout.',
  },
  geometry: {
    id: 'digital-geometry-1',
    distanceBasis: 'SOD + ODD',
    sod: { value: 100, unit: 'mm' },
    sdd: { value: '', unit: 'mm' },
    odd: { value: 10, unit: 'mm' },
    availableSourceDistance: { value: 200, unit: 'mm' },
    geometryRestrictions: 'Keep source and detector normal to the controlled inspection area.',
    requiredMaximumUg: { value: 0.1, unit: 'mm' },
    requiredMaximumEffectivePixel: { value: 0.2, unit: 'mm' },
    inspectionAreaId: 'inspection-area-1',
    requiredOverlapPercent: 20,
    excessiveOverlapThresholdPercent: 70,
    optimizeExposureCount: true,
    optimizeSodForUg: false,
    optimizeOdd: false,
    levelThreeApprovalReference: 'L3-001 / coverage optimization approval',
  },
  visual: {
    id: 'visual-template-1',
    sourcePosition: { x: 0.5, y: 0.05 },
    detectorPosition: { x: 0.5, y: 0.95 },
    detectorRotationDegrees: 0,
    beamCenter: { x: 0.5, y: 0.5 },
    beamAngleDegrees: 90,
    inspectionAreaId: 'inspection-area-1',
    leadMarkers: 'Place EXP ID, orientation, and datum markers outside the area of interest.',
  },
  iqiRules: {
    id: 'iqi-planning-1',
    basis: {
      id: 'iqi-basis-1',
      catalogRecordId: 'iqi-record-1',
      catalogRevisionId: 'iqi-revision-1',
      catalogRevision: 1,
      snapshot: {
        standard: 'Controlled IQI standard',
        standardRevision: 'REV C',
        materialGroup: 'Aluminum alloys',
        iqiType: 'Wire',
        wallTechnique: 'Single Wall',
        imageTechnique: 'SWSI',
        thicknessUnit: 'mm',
        placementRule: 'Source side adjacent to each controlled zone',
        rules: [
          {
            id: 'iqi-rule-1',
            minimumThickness: 0,
            maximumThickness: 10,
            iqiMaterial: 'Aluminum',
            designation: 'WIRE-10',
            requiredWire: 'W10',
            requiredHole: '',
            requiredSensitivity: '2 percent or better',
            placement: 'Source side',
            shimRequirement: 'Use equal-material shim when required',
          },
          {
            id: 'iqi-rule-2',
            minimumThickness: 10,
            maximumThickness: 20,
            iqiMaterial: 'Aluminum',
            designation: 'WIRE-12',
            requiredWire: 'W12',
            requiredHole: '',
            requiredSensitivity: '2 percent or better',
            placement: 'Source side',
            shimRequirement: 'Use equal-material shim when required',
          },
        ],
      },
      standard: 'Controlled IQI standard',
      standardRevision: 'REV C',
      iqiType: 'Wire',
      material: 'Aluminum',
      materialGroup: 'Aluminum alloys',
      placementRule: 'Source side adjacent to each controlled zone',
    },
    zoneOutputs: [
      {
        id: 'iqi-output-1',
        thicknessZoneId: 'thickness-zone-1',
        governingThickness: 10,
        thicknessUnit: 'mm',
        iqiMaterial: 'Aluminum',
        designation: 'WIRE-12',
        requiredWire: 'W12',
        requiredHole: '',
        requiredSensitivity: '2 percent or better',
        placement: 'Source side',
        shimRequirement: 'Use equal-material shim when required',
        governing: false,
        overrideId: '',
      },
      {
        id: 'iqi-output-2',
        thicknessZoneId: 'thickness-zone-2',
        governingThickness: 12,
        thicknessUnit: 'mm',
        iqiMaterial: 'Aluminum',
        designation: 'WIRE-12',
        requiredWire: 'W12',
        requiredHole: '',
        requiredSensitivity: '2 percent or better',
        placement: 'Source side',
        shimRequirement: 'Use equal-material shim when required',
        governing: true,
        overrideId: '',
      },
    ],
  },
  viewingPresets: [{
    id: 'VP-01',
    name: 'General Interpretation',
    windowLevel: 100,
    windowWidth: 500,
    zoom: 100,
    sharpness: 'Qualified neutral sharpness',
    permittedProcessing: 'Window, level, zoom, and qualified LUT only',
    lut: 'Linear qualified LUT',
    invert: false,
  }],
  processingPolicy: {
    permittedProcessing: 'Reversible window, level, zoom, and qualified LUT adjustments',
    prohibitedProcessing: 'No destructive filtering, interpolation, or removal of indications',
  },
  acceptanceProfiles: [{
    id: 'AC-01',
    name: 'Controlled Product Acceptance',
    standard: completeAcceptance.acceptanceStandard,
    revision: 'REV B',
    acceptanceClass: completeAcceptance.acceptanceClass,
    grade: completeAcceptance.acceptanceGrade,
    level: 'Level 2',
    applicableClause: completeAcceptance.acceptanceClause,
    drawingRequirement: completeGeneral.drawingReference,
    customerRequirement: 'Customer contract C-1',
    requirementText: completeAcceptance.acceptanceText,
  }],
  overrides: [],
});

const digitalPlanningCalculation = (planning: RtDigitalPlanning) => calculateRtDigitalPlanning({
  geometry: {
    distanceBasis: planning.geometry.distanceBasis,
    sod: planning.geometry.sod,
    sdd: planning.geometry.sdd,
    odd: planning.geometry.odd,
    focalSpotSize: { value: 1, unit: 'mm' },
    requiredMaximumUg: planning.geometry.requiredMaximumUg,
    detectorPixelSize: { value: 200, unit: 'um' },
    detectorActiveWidth: { value: 400, unit: 'mm' },
    detectorActiveHeight: { value: 300, unit: 'mm' },
    requiredMaximumEffectivePixel: planning.geometry.requiredMaximumEffectivePixel,
  },
  inspectionAreaWidth: { value: 500, unit: 'mm' },
  inspectionAreaHeight: { value: 250, unit: 'mm' },
  requiredOverlapPercent: planning.geometry.requiredOverlapPercent,
  excessiveOverlapThresholdPercent: planning.geometry.excessiveOverlapThresholdPercent,
});

const digitalAcquisitionPlan = (
  descriptor: RtDigitalExposureGridDescriptor,
  index: number,
): RtDigitalAcquisitionPlan => {
  const zoneNumber = index + 1;
  return {
    id: `acquisition-plan-${zoneNumber}`,
    gridPlacement: {
      id: `grid-placement-${zoneNumber}`,
      row: descriptor.row,
      column: descriptor.column,
      centerX: descriptor.centerXmm,
      centerY: descriptor.centerYmm,
      unit: 'mm',
      detectorOrientation: descriptor.orientation,
    },
    visual: {
      id: `exposure-visual-${zoneNumber}`,
      sourcePosition: { x: 0.5, y: 0.05 },
      detectorPosition: { x: 0.5, y: 0.95 },
      detectorRotationDegrees: 0,
      beamCenter: { x: zoneNumber === 1 ? 0.35 : 0.65, y: 0.5 },
      beamAngleDegrees: 90,
      inspectionAreaId: 'inspection-area-1',
      leadMarkers: `${descriptor.id}, datum A, orientation arrow`,
    },
    representativeImage: {
      id: `representative-image-${zoneNumber}`,
      name: `${descriptor.id}-representative.png`,
      mimeType: 'image/png',
      size: 2048 + index,
      sha256: zoneNumber === 1
        ? 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
        : 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
    },
    iqiAssignment: {
      id: `iqi-assignment-${zoneNumber}`,
      zoneOutputId: `iqi-output-${zoneNumber}`,
      designation: 'WIRE-12',
      requiredWire: 'W12',
      requiredHole: '',
      shimRequirement: 'Use equal-material shim when required',
      positionDescription: 'Source side adjacent to the interpreted zone',
      position: { x: zoneNumber === 1 ? 0.2 : 0.8, y: 0.2 },
    },
    interpretationAreas: [{
      id: `interpretation-area-${zoneNumber}`,
      areaId: `IA-${String(zoneNumber).padStart(2, '0')}`,
      description: `Controlled interpretation area for ${descriptor.id}`,
      inspectionAreaId: 'inspection-area-1',
      thicknessZoneId: `thickness-zone-${zoneNumber}`,
      position: { x: 0, y: 0, width: 1, height: 1, rotationDegrees: 0 },
      thicknessMinimum: zoneNumber === 1 ? 8 : 10,
      thicknessMaximum: zoneNumber === 1 ? 10 : 12,
      thicknessUnit: 'mm',
      viewingPresetId: 'VP-01',
      windowLevel: 100,
      windowWidth: 500,
      zoom: 100,
      sharpness: 'Qualified neutral sharpness',
      permittedProcessing: 'Window, level, zoom, and qualified LUT only',
      lut: 'Linear qualified LUT',
      invert: false,
      acceptanceProfileId: 'AC-01',
    }],
  };
};

const digitalAcquisition = (
  descriptor: RtDigitalExposureGridDescriptor,
  index: number,
) => createRtDigitalAcquisition({
  plan: digitalAcquisitionPlan(descriptor, index),
  id: `dda-acquisition-${index}`,
  viewId: descriptor.id,
  description: `Static acquisition ${descriptor.id}`,
  orientation: descriptor.orientation,
  inspectionZone: `AREA-01 / TZ-${String(index + 1).padStart(2, '0')}`,
  referenceAttachmentId: 'part-reference-1',
  wallTechnique: 'SWSI',
  sdd: 110,
  sddUnit: 'mm',
  sod: 100,
  sodUnit: 'mm',
  odd: 10,
  oddUnit: 'mm',
  thicknessDescription: 'Controlled range',
  thicknessMin: 8,
  thicknessMax: 12,
  requiredUg: 0.1,
  tubeVoltage: 120,
  tubeCurrent: 5,
  exposureTime: 2,
  exposureTimeUnit: 's',
  integrationTime: 1,
  integrationTimeUnit: 'ms',
  frameCount: 4,
  framesAveraged: 4,
  filter: '1 mm Cu',
  collimation: 'To inspection zone',
  iqiOverride: '',
  coverage: `Calculated FOV footprint for ${descriptor.id} with 20 percent required overlap`,
  imageNaming: `PART-100-${descriptor.id}`,
  markingInstructions: `Marker ${descriptor.id}`,
  notes: 'Static acquisition',
});

export function createCompleteDigitalDocument(status: RtPtDocumentStatus = 'draft'): Extract<RtPtDocumentV3, { method: 'RT-Digital' }> {
  const planning = createCompleteDigitalPlanning();
  const calculation = digitalPlanningCalculation(planning);
  const acquisitions = calculation.orientation.landscape.coverage.grid.map(digitalAcquisition);
  const document = createRtPtDocument({
    ...controlledBase,
    approvals: [
      {
        role: 'prepared',
        name: 'Technique Preparer',
        personnelId: 'PREP-001',
        certificationBasis: 'Company written practice',
        certificationRevision: 'C',
        date: '2026-07-20',
      },
      ...controlledBase.approvals,
      {
        role: 'quality',
        name: 'Quality Approver',
        personnelId: 'QA-001',
        certificationBasis: 'Quality authorization matrix',
        certificationRevision: 'B',
        date: '2026-07-20',
      },
      {
        role: 'customer',
        name: 'Customer Approver',
        personnelId: 'CUS-001',
        certificationBasis: 'Contract approval authority',
        certificationRevision: 'A',
        date: '2026-07-20',
      },
    ],
    status,
    method: 'RT-Digital',
    technique: {
      ...emptyRtDigitalSheet,
      general: completeGeneral,
      workflow: 'Static',
      source: {
        ...emptyRtDigitalSheet.source,
        sourceType: 'X-ray',
        manufacturer: 'Source Maker',
        model: 'XR-200',
        serialNumber: 'XR-SN-1',
        calibrationRequirement: 'SOURCE-CAL-1 REV A current within the controlled procedure interval',
        focalSpotSize: 1,
      },
      acquisitionDefaults: {
        ...emptyRtDigitalSheet.acquisitionDefaults,
        wallTechnique: 'SWSI',
        sdd: 110,
        sod: 100,
        odd: 10,
        requiredUg: 0.1,
      },
      system: {
        ...emptyRtDigitalSheet.system,
        ddaType: 'Flat panel',
        manufacturer: 'Detector Maker',
        model: 'DDA-1',
        serialNumber: 'DDA-SN-1',
        activeAreaWidth: 400,
        activeAreaHeight: 300,
        matrixColumns: 2000,
        matrixRows: 1500,
        pixelSize: 200,
        bitDepth: 16,
        detectorMode: 'Full',
        softwareName: 'Acquire',
        softwareVersion: '3.1',
        systemQualificationReference: 'QUAL-DDA-1 REV C',
        performanceBaselineReference: 'BASE-DDA-1 REV B',
      },
      detectorPerformance: {
        detectorSrb: 200,
        detectorSrbUnit: 'um',
        imageSrb: 210,
        imageSrbUnit: 'um',
        badPixelMap: currentDigitalStatus('BPM-1'),
        calibration: currentDigitalStatus('CAL-1'),
        stability: currentDigitalStatus('STAB-1'),
      },
      imageProcessing: {
        windowLevel: 100,
        windowWidth: 500,
        zoom: 100,
        noiseReduction: 'Qualified setting NR-1',
        contrastEnhancement: 'Qualified setting CE-1',
        processingProcedure: 'PROC-IMG-1 REV A',
      },
      displayAndStorage: {
        displayManufacturer: 'Display Maker',
        displayModel: 'MON-1',
        displaySerialNumber: 'MON-SN-1',
        viewerSoftware: 'Viewer',
        viewerSoftwareVersion: '2.0',
        displayQualificationReference: 'DISPLAY-QUAL-1',
        storageFormat: 'DICONDE profile defined below',
        archiveLocation: 'Controlled archive A',
        retentionPeriod: 'Per contract',
        rawDataPreservation: 'Preserve raw source data without destructive overwrite',
        dicondeProfileReference: 'DICONDE-PROFILE-1 REV A',
      },
      iqi: {
        type: 'Duplex wire',
        standard: 'Controlled IQI standard',
        designation: 'DW-10',
        material: 'Same alloy group',
        thickness: 10,
        thicknessUnit: 'mm',
        placement: 'Source side',
        requiredSensitivity: 'Per controlled reference',
        requiredUg: 0.1,
        requiredUgUnit: 'mm',
        requiredSnrOrNormalizedSnr: 'Normalized SNR per controlled qualification reference',
        requiredContrastSensitivityOrCnr: 'CNR requirement per controlled qualification reference',
      },
      acceptance: completeAcceptance,
      acquisitions,
      techniqueNotes: 'Static DDA workflow only.',
      planning,
    },
  }) as Extract<RtPtDocumentV3, { method: 'RT-Digital' }>;
  return bindFixtureApproval(document, status);
}

export function createCompletePtDocument(
  method: PenetrantMethod = 'B',
  penetrantType: PenetrantType = 'Type I',
  status: RtPtDocumentStatus = 'draft',
): Extract<RtPtDocumentV3, { method: 'PT' }> {
  const document = createRtPtDocument({
    ...controlledBase,
    status,
    method: 'PT',
    technique: {
      ...emptyPtSheet,
      general: completeGeneral,
      materials: {
        ...emptyPtSheet.materials,
        penetrantType,
        method,
        sensitivityLevel: penetrantType === 'Type I' ? '1/2' : '',
        systemFamily: 'Qualified family QF-1',
        qualificationReference: 'MATERIAL-QUAL-1 REV A',
        developerForm: 'Form d',
        penetrant: { manufacturer: 'Product Maker', designation: 'PEN-1' },
        cleaner: { manufacturer: 'Product Maker', designation: 'CLEAN-1' },
        remover: { manufacturer: 'Product Maker', designation: 'REM-1' },
        emulsifier: { manufacturer: 'Product Maker', designation: 'EMU-1' },
        developer: { manufacturer: 'Product Maker', designation: 'DEV-1' },
      },
      surfacePrep: {
        cleaningMethod: 'Approved cleaning process',
        cleaningDetails: 'Remove contamination before penetrant application',
        cleaningRestrictions: 'No unapproved media',
        surfaceCondition: 'Clean and dry',
        dryingMethod: 'Air',
        dryingTime: 10,
        dryingTimeUnit: 'min',
        dryingTemperature: 25,
        dryingTemperatureUnit: 'degC',
      },
      application: {
        applicationMethod: 'Spray',
        dwellTime: 20,
        dwellTimeUnit: 'min',
        partTemperatureMin: 10,
        partTemperatureMax: 40,
        partTemperatureUnit: 'degC',
        penetrantTemperatureMin: 10,
        penetrantTemperatureMax: 40,
        penetrantTemperatureUnit: 'degC',
      },
      removal: {
        methodA: {
          instructions: 'Controlled water rinse',
          pressureMin: 1,
          pressureMax: 2,
          pressureUnit: 'bar',
          temperatureMin: 20,
          temperatureMax: 30,
          temperatureUnit: 'degC',
        },
        methodBD: {
          type: method === 'B' ? 'Lipophilic' : 'Hydrophilic',
          concentration: method === 'D' ? 10 : '',
          concentrationUnit: method === 'D' ? '%' : '',
          contactTime: 2,
          contactTimeUnit: 'min',
          applicationMethod: 'Immersion',
          postEmulsifierRinseInstructions: 'Water rinse after emulsification',
        },
        methodC: { removerInstructions: 'Wipe with approved remover; do not flush.' },
        methodD: {
          preRinseInstructions: 'Controlled pre-rinse before hydrophilic emulsifier',
          finalRinseInstructions: 'Controlled final rinse after emulsification',
        },
      },
      development: {
        developerApplication: 'Spray',
        developmentTime: 10,
        developmentTimeUnit: 'min',
        instructions: 'Apply a uniform developer coating',
      },
      conditions: {
        requiredUvAMin: penetrantType === 'Type I' ? 1000 : '',
        uvAUnit: penetrantType === 'Type I' ? 'uW/cm2' : '',
        ambientVisibleLightMax: penetrantType === 'Type I' ? 20 : '',
        whiteLightMin: penetrantType === 'Type II' ? 1000 : '',
        visibleLightUnit: 'lux',
        darkAdaptationTime: penetrantType === 'Type I' ? 5 : '',
        darkAdaptationTimeUnit: penetrantType === 'Type I' ? 'min' : '',
        equipmentRequirements: 'Calibrated meters and qualified viewing area',
      },
      acceptance: completeAcceptance,
      postCleaning: {
        instructions: 'Remove process residues after inspection',
        corrosionProtection: 'Apply approved protection when required',
      },
      techniqueNotes: 'No performed indications or disposition are stored here.',
    },
  }) as Extract<RtPtDocumentV3, { method: 'PT' }>;
  return bindFixtureApproval(document, status);
}
