import { emptyPtSheet, type PenetrantMethod, type PenetrantType } from '@/types/penetrant';
import { emptyRtDigitalSheet } from '@/types/rtDigital';
import { emptyRtFilmSheet } from '@/types/rtFilm';
import {
  createRtDigitalAcquisition,
  createRtFilmExposureView,
  createRtPtDocument,
} from '@/lib/rtPtDocumentCodec';
import type { RtPtDocumentStatus, RtPtDocumentV3 } from '@/types/rtPtDocument';

export const completeGeneral = {
  partName: 'Test casting',
  partNumber: 'PART-100',
  vendorCode: 'VENDOR-7',
  partRevisionOrConfiguration: 'REV-B',
  material: 'Aluminum alloy',
  surfaceFinish: 'As cast',
  inspectionArea: 'Entire part',
  thickness: 10,
  thicknessUnit: 'mm' as const,
  drawingReference: 'DWG-100 REV B',
  procedureNumber: 'PROC-NDT-1',
  inspectionStage: 'Final' as const,
  inspectorLevel: 'II' as const,
  date: '2026-07-20',
};

export const completeAcceptance = {
  acceptanceStandard: 'PRODUCT-SPEC-1',
  acceptanceClause: '7.4',
  acceptanceText: 'Apply the controlled product-specification acceptance text.',
  acceptanceClass: 'Class 2',
  acceptanceGrade: 'Grade C',
  specialRequirements: 'None',
};

const controlledBase = {
  documentId: '00000000-0000-4000-8000-000000000099',
  documentControl: {
    number: 'RTPT-100',
    title: 'Controlled NDT Technique',
    revision: 'B',
    revisionDate: '2026-07-20',
    effectiveDate: '2026-07-21',
    changeSummary: 'V3 planned technique',
  },
  revisionHistory: [{
    id: 'revision-b',
    revision: 'B',
    date: '2026-07-20',
    description: 'V3 planned technique',
    author: 'Planner',
  }],
  organization: { name: 'NDT Laboratory', site: 'Site A' },
  job: { customer: 'Customer', contract: 'C-1', purchaseOrder: 'PO-1', workOrder: 'WO-1' },
  unitSystem: 'SI' as const,
  controlledReferences: [{
    type: 'Product specification',
    title: 'Product acceptance specification',
    number: 'PRODUCT-SPEC-1',
    revision: 'B',
    clauseOrNote: 'Clause 7.4',
  }],
  approvals: [{
    role: 'ndt-level-3' as const,
    name: 'Level Three',
    personnelId: 'L3-001',
    certificationBasis: 'Written practice',
    certificationRevision: 'C',
    date: '2026-07-20',
  }],
};

const filmView = (index: number) => createRtFilmExposureView({
  id: `film-view-${index}`,
  viewId: `V${index}`,
  description: `Planned view ${index}`,
  orientation: `${(index - 1) * 90} deg`,
  inspectionZone: `Zone ${index}`,
  referenceAttachmentId: `ATT-${index}`,
  wallTechnique: 'SWSI',
  sfd: 110,
  sfdUnit: 'mm',
  sod: 100,
  sodUnit: 'mm',
  ofd: 10,
  ofdUnit: 'mm',
  thicknessDescription: 'Controlled range',
  thicknessMin: 8,
  thicknessMax: 12,
  thicknessUnit: 'mm',
  requiredUg: 0.1,
  requiredUgUnit: 'mm',
  iqiOverride: 'Use global IQI plan',
  tubeVoltage: 120,
  tubeCurrent: 5,
  exposureTime: 2,
  exposureTimeUnit: 'min',
  filter: 'None',
  collimation: 'To inspection zone',
  filmDesignation: 'FILM-A',
  filmSize: '35 x 43 cm',
  maxParts: 1,
  maxCassettes: 1,
  beamAngle: 90,
  screenOverride: 'None',
  overlap: 'Witnessed overlap required',
  identification: `Lead marker V${index}`,
  notes: 'Planned only',
});

export function createCompleteFilmDocument(status: RtPtDocumentStatus = 'draft'): Extract<RtPtDocumentV3, { method: 'RT-Film' }> {
  return createRtPtDocument({
    ...controlledBase,
    status,
    method: 'RT-Film',
    technique: {
      ...emptyRtFilmSheet,
      general: completeGeneral,
      exposureDefaults: {
        ...emptyRtFilmSheet.exposureDefaults,
        wallTechnique: 'SWSI',
        sfd: 110,
        sod: 100,
        ofd: 10,
        requiredUg: 0.1,
      },
      source: {
        ...emptyRtFilmSheet.source,
        sourceType: 'X-ray',
        manufacturer: 'Source Maker',
        model: 'XR-200',
        serialNumber: 'XR-SN-1',
        calibrationRequirement: 'Calibration within the controlled procedure interval',
        xRay: { focalSpotSize: 1, focalSpotSizeUnit: 'mm' },
      },
      filmSystem: {
        ...emptyRtFilmSheet.filmSystem,
        manufacturer: 'Film Maker',
        filmDesignation: 'FILM-A',
        filmClass: 'Class I',
        requiredDensityMin: 1.5,
        requiredDensityMax: 4,
        processingSystem: 'Automatic processor P-1',
        processingMethod: 'Automatic',
        processingTime: 7,
        processingTimeUnit: 'min',
        processingTemperature: 28,
        processingTemperatureTolerance: 1,
        processingTemperatureUnit: 'degC',
        frontScreen: { material: 'Lead', thickness: 0.1, thicknessUnit: 'mm' },
        backScreen: { material: 'Lead', thickness: 0.1, thicknessUnit: 'mm' },
        cassetteType: 'Rigid',
        viewingEquipment: 'Viewer V-1',
      },
      iqi: {
        ...emptyRtFilmSheet.iqi,
        type: 'Hole',
        standard: 'Controlled IQI standard',
        designation: 'IQI-10',
        shim: 'Shim S-1',
        block: 'Block B-1',
        material: 'Same alloy group',
        thickness: 10,
        placement: 'Source side',
        requiredSensitivity: 'Per controlled reference',
        imageQualityLevel: 'Per controlled reference',
        requiredUg: 0.1,
      },
      acceptance: completeAcceptance,
      exposureViews: [1, 2, 3, 4].map(filmView),
      techniqueNotes: 'All entries are planned or required values.',
    },
  }) as Extract<RtPtDocumentV3, { method: 'RT-Film' }>;
}

export function createCompletePs811000FilmDocument(
  status: RtPtDocumentStatus = 'draft',
): Extract<RtPtDocumentV3, { method: 'RT-Film' }> {
  const document = createCompleteFilmDocument(status);
  document.technique.ps811000Applicable = true;
  document.controlledReferences.push({
    type: 'Process specification',
    title: 'Controlled radiographic process specification',
    number: 'PS811000E',
    revision: 'C1',
    clauseOrNote: 'Verified calculation and lookup basis',
  });
  document.technique.filmSystem.viewingMode = 'single';
  document.technique.filmSystem.viewerOutputCandelaPerSquareMeter = 100000;
  document.technique.filmSystem.individualFilmDensityMinimum = '';
  document.technique.iqi.requiredUg = '';
  document.technique.exposureDefaults = {
    ...document.technique.exposureDefaults,
    ps811000EnergyCurve: 'aluminum-magnesium',
    ps811000EquivalenceMaterial: 'Aluminum 1100 / 6061',
    ps811000ThicknessBasis: 'entered-thickness',
    machineTechniqueReference: 'MACHINE-TABLE-1 REV A',
    coverageDiameter: 10,
    coverageDiameterUnit: 'mm',
    thicknessMin: 8,
    thicknessMax: 12,
    tubeVoltage: 70,
    tubeCurrent: 5,
    exposureTime: 2,
    exposureTimeUnit: 'min',
    requiredUg: '',
  };
  document.technique.exposureViews = document.technique.exposureViews.map((view) => ({
    ...view,
    ps811000EnergyCurve: 'aluminum-magnesium',
    ps811000EquivalenceMaterial: 'Aluminum 1100 / 6061',
    ps811000ThicknessBasis: 'entered-thickness',
    machineTechniqueReference: 'MACHINE-TABLE-1 REV A',
    coverageDiameter: 10,
    coverageDiameterUnit: 'mm',
    tubeVoltage: 70,
    requiredUg: '',
  }));
  return document;
}

const digitalAcquisition = (index: number) => createRtDigitalAcquisition({
  id: `dda-acquisition-${index}`,
  viewId: `D${index}`,
  description: `Static acquisition ${index}`,
  orientation: `${(index - 1) * 90} deg`,
  inspectionZone: `Digital zone ${index}`,
  referenceAttachmentId: `DDA-ATT-${index}`,
  wallTechnique: 'SWSI',
  sdd: 110,
  sddUnit: 'mm',
  sod: 100,
  sodUnit: 'mm',
  odd: 10,
  oddUnit: 'mm',
  thicknessDescription: 'Controlled range',
  thicknessMin: 8,
  thicknessMax: 12,
  requiredUg: 0.1,
  tubeVoltage: 120,
  tubeCurrent: 5,
  exposureTime: 2,
  exposureTimeUnit: 's',
  integrationTime: 1,
  integrationTimeUnit: 'ms',
  frameCount: 4,
  framesAveraged: 4,
  filter: 'None',
  collimation: 'To inspection zone',
  iqiOverride: 'Use global IQI plan',
  coverage: 'Entire identified zone',
  imageNaming: `PART-D${index}`,
  markingInstructions: `Marker D${index}`,
  notes: 'Static acquisition',
});

export function createCompleteDigitalDocument(status: RtPtDocumentStatus = 'draft'): Extract<RtPtDocumentV3, { method: 'RT-Digital' }> {
  return createRtPtDocument({
    ...controlledBase,
    status,
    method: 'RT-Digital',
    technique: {
      ...emptyRtDigitalSheet,
      general: completeGeneral,
      workflow: 'Static',
      source: {
        ...emptyRtDigitalSheet.source,
        sourceType: 'X-ray',
        manufacturer: 'Source Maker',
        model: 'XR-200',
        serialNumber: 'XR-SN-1',
        calibrationRequirement: 'Calibration within the controlled procedure interval',
        focalSpotSize: 1,
      },
      acquisitionDefaults: {
        ...emptyRtDigitalSheet.acquisitionDefaults,
        wallTechnique: 'SWSI',
        sdd: 110,
        sod: 100,
        odd: 10,
        requiredUg: 0.1,
      },
      system: {
        ...emptyRtDigitalSheet.system,
        ddaType: 'Flat panel',
        manufacturer: 'Detector Maker',
        model: 'DDA-1',
        serialNumber: 'DDA-SN-1',
        activeAreaWidth: 400,
        activeAreaHeight: 400,
        matrixColumns: 2048,
        matrixRows: 2048,
        pixelSize: 200,
        bitDepth: 16,
        detectorMode: 'Full',
        softwareName: 'Acquire',
        softwareVersion: '3.1',
        systemQualificationReference: 'QUAL-DDA-1 REV C',
        performanceBaselineReference: 'BASE-DDA-1 REV B',
      },
      detectorPerformance: {
        detectorSrb: 200,
        detectorSrbUnit: 'um',
        imageSrb: 210,
        imageSrbUnit: 'um',
        badPixelMap: { reference: 'BPM-1', date: '2026-07-01', dueDate: '2027-07-01', status: 'Required current' },
        calibration: { reference: 'CAL-1', date: '2026-07-01', dueDate: '2027-07-01', status: 'Required current' },
        stability: { reference: 'STAB-1', date: '2026-07-01', dueDate: '2027-07-01', status: 'Required current' },
      },
      imageProcessing: {
        windowLevel: 100,
        windowWidth: 500,
        zoom: 100,
        noiseReduction: 'Qualified setting NR-1',
        contrastEnhancement: 'Qualified setting CE-1',
        processingProcedure: 'PROC-IMG-1 REV A',
      },
      displayAndStorage: {
        displayManufacturer: 'Display Maker',
        displayModel: 'MON-1',
        displaySerialNumber: 'MON-SN-1',
        viewerSoftware: 'Viewer',
        viewerSoftwareVersion: '2.0',
        displayQualificationReference: 'DISPLAY-QUAL-1',
        storageFormat: 'DICONDE profile defined below',
        archiveLocation: 'Controlled archive A',
        retentionPeriod: 'Per contract',
        rawDataPreservation: 'Preserve raw source data without destructive overwrite',
        dicondeProfileReference: 'DICONDE-PROFILE-1 REV A',
      },
      iqi: {
        type: 'Duplex wire',
        standard: 'Controlled IQI standard',
        designation: 'DW-10',
        material: 'Same alloy group',
        thickness: 10,
        thicknessUnit: 'mm',
        placement: 'Source side',
        requiredSensitivity: 'Per controlled reference',
        requiredUg: 0.1,
        requiredUgUnit: 'mm',
        requiredSnrOrNormalizedSnr: 'Normalized SNR per controlled qualification reference',
        requiredContrastSensitivityOrCnr: 'CNR requirement per controlled qualification reference',
      },
      acceptance: completeAcceptance,
      acquisitions: [digitalAcquisition(1), digitalAcquisition(2)],
      techniqueNotes: 'Static DDA workflow only.',
    },
  }) as Extract<RtPtDocumentV3, { method: 'RT-Digital' }>;
}

export function createCompletePtDocument(
  method: PenetrantMethod = 'B',
  penetrantType: PenetrantType = 'Type I',
  status: RtPtDocumentStatus = 'draft',
): Extract<RtPtDocumentV3, { method: 'PT' }> {
  return createRtPtDocument({
    ...controlledBase,
    status,
    method: 'PT',
    technique: {
      ...emptyPtSheet,
      general: completeGeneral,
      materials: {
        ...emptyPtSheet.materials,
        penetrantType,
        method,
        sensitivityLevel: penetrantType === 'Type I' ? '1/2' : '',
        systemFamily: 'Qualified family QF-1',
        qualificationReference: 'MATERIAL-QUAL-1 REV A',
        developerForm: 'Form d',
        penetrant: { manufacturer: 'Product Maker', designation: 'PEN-1' },
        cleaner: { manufacturer: 'Product Maker', designation: 'CLEAN-1' },
        remover: { manufacturer: 'Product Maker', designation: 'REM-1' },
        emulsifier: { manufacturer: 'Product Maker', designation: 'EMU-1' },
        developer: { manufacturer: 'Product Maker', designation: 'DEV-1' },
      },
      surfacePrep: {
        cleaningMethod: 'Approved cleaning process',
        cleaningDetails: 'Remove contamination before penetrant application',
        cleaningRestrictions: 'No unapproved media',
        surfaceCondition: 'Clean and dry',
        dryingMethod: 'Air',
        dryingTime: 10,
        dryingTimeUnit: 'min',
        dryingTemperature: 25,
        dryingTemperatureUnit: 'degC',
      },
      application: {
        applicationMethod: 'Spray',
        dwellTime: 20,
        dwellTimeUnit: 'min',
        partTemperatureMin: 10,
        partTemperatureMax: 40,
        partTemperatureUnit: 'degC',
        penetrantTemperatureMin: 10,
        penetrantTemperatureMax: 40,
        penetrantTemperatureUnit: 'degC',
      },
      removal: {
        methodA: {
          instructions: 'Controlled water rinse',
          pressureMin: 1,
          pressureMax: 2,
          pressureUnit: 'bar',
          temperatureMin: 20,
          temperatureMax: 30,
          temperatureUnit: 'degC',
        },
        methodBD: {
          type: method === 'B' ? 'Lipophilic' : 'Hydrophilic',
          concentration: method === 'D' ? 10 : '',
          concentrationUnit: method === 'D' ? '%' : '',
          contactTime: 2,
          contactTimeUnit: 'min',
          applicationMethod: 'Immersion',
          postEmulsifierRinseInstructions: 'Water rinse after emulsification',
        },
        methodC: { removerInstructions: 'Wipe with approved remover; do not flush.' },
        methodD: {
          preRinseInstructions: 'Controlled pre-rinse before hydrophilic emulsifier',
          finalRinseInstructions: 'Controlled final rinse after emulsification',
        },
      },
      development: {
        developerApplication: 'Spray',
        developmentTime: 10,
        developmentTimeUnit: 'min',
        instructions: 'Apply a uniform developer coating',
      },
      conditions: {
        requiredUvAMin: penetrantType === 'Type I' ? 1000 : '',
        uvAUnit: penetrantType === 'Type I' ? 'uW/cm2' : '',
        ambientVisibleLightMax: penetrantType === 'Type I' ? 20 : '',
        whiteLightMin: penetrantType === 'Type II' ? 1000 : '',
        visibleLightUnit: 'lux',
        darkAdaptationTime: penetrantType === 'Type I' ? 5 : '',
        darkAdaptationTimeUnit: penetrantType === 'Type I' ? 'min' : '',
        equipmentRequirements: 'Calibrated meters and qualified viewing area',
      },
      acceptance: completeAcceptance,
      postCleaning: {
        instructions: 'Remove process residues after inspection',
        corrosionProtection: 'Apply approved protection when required',
      },
      techniqueNotes: 'No performed indications or disposition are stored here.',
    },
  }) as Extract<RtPtDocumentV3, { method: 'PT' }>;
}
